name: Branch Conflict Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install requests

      - name: Run Conflict Check Script
        run: |
          . venv/bin/activate
          python .github/scripts/check_conflicts.py

